# To change this template, choose Tools | Templates
# and open the template in the editor.
#Datos de punto de atencion
#urlUtileria=http://64.225.154.55:8080/utilerias/servlet/GetFiles
#urlSendServer=/usr/local/apache-tomcat-5.5.20/webapps/crmBayer/archivos
#nomCarpeta=archivos
#serverSend=http://64.225.154.55:8080/crmBayer/archivos
key=test:testpass
#Host=http://ciacloud2.dyndns.org:8088/apps/
Host=https://seyl.mx/apps/globale/
ServiceLogin=usuarios/login/

UsuarioGlobal=UsuarioGLOBALProd
ClaveAccesoGlobal=ClaveAccesoGLOBAL#PROD

HostItems=https://www.vectordelta.com.mx:23958/UnionGroup/API/Query/MasterDataGLOBAL/
HostGlobalDev=https://www.vectordelta.com.mx:23958/UnionGroup/API/Queries/Query/MasterDataGLOBAL/
HostGlobalInsert=https://www.vectordelta.com.mx:23958/UnionGroup/API/Insert/Production/

#Ruta para guardar los archivos pdf
project.root.path=C:/uniogroup/documentos
#Service+Modulo+Funcionalidad#
ServiceInvOcupacionAlmacen
#ServiceEnvEstatusEnvios

ServiceAdressGlobal=Address/
ServiceAddAdressGlobal=uniongroup/consignatarios/

ServiceProductosGlobal=uniongroup/productos/
ServiceItemsGlobal=Items/

# ===== \u00d3RDENES DE COMPRA =====
ServiceOrdenCompra=uniongroup/ordenescompra/
ServiceOrdenCompraConfirm=uniongroup/ordenescompraconfirm/
ServiceOrdenCompraDet=uniongroup/ordenescompradet/?docEntry=
ServicePurchaseOrderGlobal=PurchaseOrder
ServicePurchaseOrderPostGlobal=PurchaseOrderConfirm
ServiceReceiptConfirmGlobal=ReceiptConfirm

# ===== \u00d3RDENES DE VENTA =====
ServiceSalesOrderGlobal=SalesOrder
ServiceSalesOrderPostGlobal=SalesOrderConfirm
ServiceShipmentConfirmGlobal=ShipConfirm
ServiceOrdenVenta=uniongroup/ordenesventa/
ServiceOrdenVentaDet=uniongroup/ordenventadet/?docEntry=
ServiceOrdenVentaConfirm=uniongroup/ordenesventaconfirm/

ServiceOrdenVentaLE=uniongroup/ordenventale/

# ===== TRANSFERENCIAS DE ENTRADA =====
ServiceInboundTransferGlobal=InboundTransfer
ServiceTransferConfirmGlobal=TransferConfirm
ServiceTransferReceiptConfirmGlobal=TransferReceiptConfirm
ServiceTransferenciaEntrada=uniongroup/transaccionesentrada/
ServiceTransferenciaEntradaDet=uniongroup/transaccionesentradadet/?docEntry=

ServiceTransferenciaSalidaConfirm=uniongroup/tranferenciasalidaconfirm/

# ===== TRANSFERENCIAS DE SALIDA =====
ServiceOutboundTransferGlobal=OutboundTransfer
ServiceTransferenciaSalida=uniongroup/tranferenciasalida/
ServiceTransferenciaSalidaDet=uniongroup/tranferenciasalidadet/?docEntry=
ServiceTransferShipConfirmGlobal=TransferShipConfirm
ServiceOrdenSaliaLE=uniongroup/ordensalidale/

ServiceTransferenciaEntradaConfirm=uniongroup/transaccionentradaconfirm/

ServiceEcommerce = uniongroup/ecommerce/
ServiceEcommerceDet = uniongroup/ecommercedet/

ServiceItemsGlobalConfirm=ItemsConfirm
ServiceConsignatariosGlobalConfirm=AddressConfirm
ServiceConfirmationLog=uniongroup/confirmationlog/

ServiceEcommerceLE=uniongroup/ecommercele/
ServiceRetornosGlobal=ReturnRequest
ServiceRetornos=uniongroup/retornos/

ServiceProdSurt=uniongroup/productosurtido/?clave=
ServiceRetornosDet=uniongroup/retornosdet/
ServiceReturnConfirm= ReturnConfirm
ServiceRetornosPostGlobal=ReturnRequestConfirm
ServiceRetornosConfirm=uniongroup/retornosconfirm/
