# To change this template, choose Tools | Templates
# and open the template in the editor.
#Datos de punto de atencion
#urlUtileria=http://64.225.154.55:8080/utilerias/servlet/GetFiles
#urlSendServer=/usr/local/apache-tomcat-5.5.20/webapps/crmBayer/archivos
#nomCarpeta=archivos
#serverSend=http://64.225.154.55:8080/crmBayer/archivos
key=test:testpass
#Host=http://ciacloud2.dyndns.org:8088/apps/
Host=https://seyl.mx/apps/globale/
ServiceLogin=usuarios/login/

UsuarioGlobal=UsuarioGLOBALDevelopment
ClaveAccesoGlobal=ClaveAccesoGLOBAL#Development2025

HostItems=https://www.vectordelta.com.mx:81/UnionGroup/API/Query/MasterDataGLOBAL_DEV/
HostGlobalDev=https://www.vectordelta.com.mx:81/UnionGroup/API/Queries/Query/MasterDataGLOBAL_DEV/
HostGlobalInsert=https://www.vectordelta.com.mx:81/UnionGroup/API/Insert/Development/

#Ruta para guardar los archivos pdf
project.root.path=C:/uniogroup/documentos
#Service+Modulo+Funcionalidad#
ServiceInvOcupacionAlmacen
#ServiceEnvEstatusEnvios

ServiceAdressGlobal=AddressGLOBAL_DEV/
ServiceAddAdressGlobal=uniongroup/consignatarios/

ServiceProductosGlobal=uniongroup/productos/
ServiceItemsGlobal=ItemsGLOBAL_DEV/

# ===== \u00d3RDENES DE COMPRA =====
ServiceOrdenCompra=uniongroup/ordenescompra/
ServiceOrdenCompraConfirm=uniongroup/ordenescompraconfirm/
ServiceOrdenCompraDet=uniongroup/ordenescompradet/?docEntry=
ServicePurchaseOrderGlobal=PurchaseOrderGLOBAL_DEV
ServicePurchaseOrderPostGlobal=PurchaseOrderConfirmDEV
ServiceReceiptConfirmGlobal=ReceiptConfirmDEV

# ===== \u00d3RDENES DE VENTA =====
ServiceSalesOrderGlobal=SalesOrderGLOBAL_DEV
ServiceSalesOrderPostGlobal=SalesOrderConfirmDEV
ServiceShipmentConfirmGlobal=ShipConfirmDEV
ServiceOrdenVenta=uniongroup/ordenesventa/
ServiceOrdenVentaDet=uniongroup/ordenventadet/?docEntry=
ServiceOrdenVentaConfirm=uniongroup/ordenesventaconfirm/

ServiceOrdenVentaLE=uniongroup/ordenventale/

# ===== TRANSFERENCIAS DE ENTRADA =====
ServiceInboundTransferGlobal=InboundTransferGLOBAL_DEV
ServiceTransferConfirmGlobal=TransferConfirmDEV
ServiceTransferReceiptConfirmGlobal=TransferReceiptConfirmDEV
ServiceTransferenciaEntrada=uniongroup/transaccionesentrada/
ServiceTransferenciaEntradaDet=uniongroup/transaccionesentradadet/?docEntry=

ServiceTransferenciaSalidaConfirm=uniongroup/tranferenciasalidaconfirm/

# ===== TRANSFERENCIAS DE SALIDA =====
ServiceOutboundTransferGlobal=OutboundTransferGLOBAL_DEV
ServiceTransferenciaSalida=uniongroup/tranferenciasalida/
ServiceTransferenciaSalidaDet=uniongroup/tranferenciasalidadet/?docEntry=
ServiceTransferShipConfirmGlobal=TransferShipConfirmDEV
ServiceOrdenSaliaLE=uniongroup/ordensalidale/

ServiceTransferenciaEntradaConfirm=uniongroup/transaccionentradaconfirm/

ServiceEcommerce = uniongroup/ecommerce/
ServiceEcommerceDet = uniongroup/ecommercedet/

ServiceItemsGlobalConfirm=ItemsConfirmDEV
ServiceConsignatariosGlobalConfirm=AddressConfirmDEV
ServiceConfirmationLog=uniongroup/confirmationlog/

ServiceEcommerceLE=uniongroup/ecommercele/
ServiceRetornosGlobal=ReturnRequestGLOBAL_DEV
ServiceRetornos=uniongroup/retornos/

ServiceProdSurt=uniongroup/productosurtido/?clave=
ServiceRetornosDet=uniongroup/retornosdet/